<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Boki</name>
   <tag></tag>
   <elementGuidId>8297a03c-1c6b-4879-9dee-e7ba4648ff0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(9) > div.chat-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='left_div']/div/div[9]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>435655aa-41ae-4b5d-84bd-4d7888f12f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chat-item</value>
      <webElementGuid>94e6adfa-8148-44b1-8c4e-fe5289c9dac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Boki</value>
      <webElementGuid>728766a9-4cdf-4d5c-8cbc-32a6f1e92e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left_div&quot;)/div[1]/div[9]/div[@class=&quot;chat-item&quot;]</value>
      <webElementGuid>29a83f15-fa09-49dc-a348-f43c721e0a5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left_div']/div/div[9]/div</value>
      <webElementGuid>248c9cc1-906d-4d46-b695-1958c1b45e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vukasin'])[1]/following::div[5]</value>
      <webElementGuid>109ab67f-d11d-4d69-8a0c-7a1a75e307d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catch You'])[1]/following::div[12]</value>
      <webElementGuid>cfaba7f1-6de7-4361-bd67-5bb082add031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div</value>
      <webElementGuid>066f2142-bdc5-4168-8d8c-db71ebcf2a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Boki' or . = 'Boki')]</value>
      <webElementGuid>7317e011-95c6-47e0-9b1a-c9e0bc5aafb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
