<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_false</name>
   <tag></tag>
   <elementGuidId>8eff44e4-b71d-46ba-b9b2-10e6f598c14a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.unread-count</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='left_div']/div/div/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5cf747ae-c014-4303-b774-2bbcca35d81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>unread-count</value>
      <webElementGuid>56738647-cf06-4bdd-b1f8-afe28c67a443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>12ce6ffe-38ec-4125-aae3-133e20da951b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left_div&quot;)/div[1]/div[1]/div[@class=&quot;chat-item&quot;]/div[@class=&quot;bottom-row&quot;]/div[@class=&quot;unread-count&quot;]</value>
      <webElementGuid>832258f1-f080-40ad-8636-d7208b53d86b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='left_div']/div/div/div/div[2]/div[2]</value>
      <webElementGuid>13976cb1-8b51-4b94-b0ee-20dc9ec2c522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zdravo Boki :)'])[1]/following::div[1]</value>
      <webElementGuid>60cacf66-01e7-4d7d-b9d9-fbc9058050a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boki'])[1]/following::div[4]</value>
      <webElementGuid>2047ee1a-442a-4b97-80be-094758e17679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='n b dz s'])[1]/preceding::div[1]</value>
      <webElementGuid>d217f026-4827-4a4f-914e-e9fde29dbff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- group chat'])[1]/preceding::div[1]</value>
      <webElementGuid>023d1e52-87ac-46be-8f2f-08f894e854c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='false']/parent::*</value>
      <webElementGuid>3874c9f6-1275-45ca-8bde-985a92d37c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div[2]</value>
      <webElementGuid>f0fefcc1-7b07-4628-9244-5f6a5cd4a4d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'false' or . = 'false')]</value>
      <webElementGuid>87a5e950-6fa0-4d1e-9928-1c43f0dc7eb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
