<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-calendar_OCT 2024OCT 2024SundaySMondayM_fa1667</name>
   <tag></tag>
   <elementGuidId>f12499e4-f7f8-4ac8-b6c2-4bbc8d7524d2</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-datepicker-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-calendar[@id='mat-datepicker-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-calendar</value>
      <webElementGuid>2657971a-7b09-4687-89d5-287a8918e012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-calendar ng-tns-c2024481049-3 ng-trigger ng-trigger-fadeInCalendar</value>
      <webElementGuid>5e0a96d4-1280-4244-9523-411f5bd24aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-datepicker-0</value>
      <webElementGuid>3aa4171c-c08b-4176-a10c-d968d217460e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OCT 2024OCT 2024SundaySMondayMTuesdayTWednesdayWThursdayTFridayFSaturdayS OCT    1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  
 
</value>
      <webElementGuid>715cef90-9d69-4120-8e22-5b540e9cad71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-datepicker-0&quot;)</value>
      <webElementGuid>4e0eb577-aaa1-43b5-abea-938fc145618a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-calendar[@id='mat-datepicker-0']</value>
      <webElementGuid>843d183d-d0f0-4d69-87b6-3d6d8e77b307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-1']/mat-datepicker-content/div[2]/mat-calendar</value>
      <webElementGuid>65d95629-b95d-40f8-9dc5-e6ddc8230ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create account'])[1]/following::mat-calendar[1]</value>
      <webElementGuid>d213c863-80bb-4088-9f6a-63d12f2bcb8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-calendar</value>
      <webElementGuid>90681190-1320-4951-a4a2-c7699cd27ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-calendar[@id = 'mat-datepicker-0' and (text() = 'OCT 2024OCT 2024SundaySMondayMTuesdayTWednesdayWThursdayTFridayFSaturdayS OCT    1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  
 
' or . = 'OCT 2024OCT 2024SundaySMondayMTuesdayTWednesdayWThursdayTFridayFSaturdayS OCT    1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  
 
')]</value>
      <webElementGuid>1bc94f1f-dbfa-40e9-9c56-4440726e3a47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
